name: phase1-hub-vpc1-destroy

on:
  push:
    branches:
      - main
  workflow_dispatch:  


permissions:
  id-token: write
  contents: read

jobs:
  terraform-destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::647132523867:role/github-actions-terraform-role-v1
          aws-region: ap-south-1

      - name: Show Terraform Files
        run: |
          pwd
          echo "Repository files:"
          ls -la
          echo ""
          echo "Terraform files:"
          find terraform -type f -name "*.tf" -print

      - name: Terraform Format Check
        run: terraform fmt -check -recursive
        working-directory: terraform

      - name: Terraform Init
        run: terraform init -input=false
        working-directory: terraform

      - name: Terraform Workspace
        run: terraform workspace show
        working-directory: terraform

      - name: Terraform State List
        run: terraform state list
        working-directory: terraform

      - name: Terraform Validate
        run: terraform validate
        working-directory: terraform

      - name: Terraform Destroy Plan
        run: terraform plan -destroy -input=false -out=tfplan-destroy
        working-directory: terraform

      - name: Terraform Destroy
        run: terraform apply -input=false -auto-approve tfplan-destroy
        working-directory: terraform 