on:
  push:
    branches:
      - main
  workflow_dispatch:


permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::647132523867:role/github-actions-terraform-role-v1
          aws-region: ap-south-1

      - name: Find VPC
        id: find-vpc
        run: |
          set -e

          echo "Searching for VPCs in ap-south-1..."

          VPC_IDS=$(aws ec2 describe-vpcs \
            --region ap-south-1 \
            --query 'Vpcs[*].VpcId' \
            --output text)

          echo "Found VPCs:"
          echo "$VPC_IDS"

          if [ -z "$VPC_IDS" ]; then
            echo "ERROR: No VPC found."
            exit 1
          fi

          COUNT=$(echo "$VPC_IDS" | wc -w)

          if [ "$COUNT" -ne 1 ]; then
            echo "ERROR: More than one VPC exists."
            echo "VPCs found:"
            echo "$VPC_IDS"
            echo ""
            echo "I will NOT automatically delete them."
            exit 1
          fi

          VPC_ID="$VPC_IDS"

          echo "Selected VPC: $VPC_ID"

          echo "vpc_id=$VPC_ID" >> "$GITHUB_OUTPUT"

      - name: Verify VPC
        env:
          VPC_ID: ${{ steps.find-vpc.outputs.vpc_id }}
        run: |
          set -e

          echo "Checking VPC: $VPC_ID"

          aws ec2 describe-vpcs \
            --vpc-ids "$VPC_ID" \
            --region ap-south-1 \
            --query 'Vpcs[0].[VpcId,CidrBlock,State]' \
            --output table